### PR TITLE
added rccl support

### PR DESCRIPTION
**Pull request by aditya4d**

### CODE REVIEW

**Comment by asroy** [comment]
@adityaatluri Could you also update READMD.md file in the root directory of this repo? There is the old instruction for dependency (currently no RCCL) and setting up environment variables.

**Comment by aditya4d** [comment]
Can you point me to it?

**Comment by asroy** [comment]
@adityaatluri I don't know how to refer it here. But you can find it in the README.md file in DeepBench root directory. There is a session under the name "AMD Benchmarks" at the end of the file.

**Comment by aditya4d** [comment]
How about now?

**Comment by asroy** [comment]
@adityaatluri I think LD_LIBRARY_PATH may also need to be updated to include RCCL lib. If that's not the case, it looks good to me.

**Comment by aditya4d** [comment]
Changed it.

**Review by asroy — APPROVED** [review]

**Pull request merged**
